### ISSUE TITLE
Windows running bug

### ISSUE THREAD

**Issue by 111Moderato** [kaldi-asr/kaldi#3902] opened 2020-02-02 12:12 UTC
Hi :
Has anyone ever run **wav-reverberate** on windows?
No error when compile and run , however,  the output wav file  is  noise.   

The command is:
`wav-reverberate --duration=3.865 F:/download/musan/speech/us-gov/speech-us-gov-0001.wav 1.wav`

The same thing happens in **wav-copy**.
Does Kaldi's IO mechanism not support windows?

**Comment by danpovey** [comment] 2020-02-02 12:17
Windows is supported, yes.  I suspect it might be related to your computer
architecture (is it ARM?) or maybe BLAS.
E.g. the data might have got byte swapped.

**Comment by 111Moderato** [comment] 2020-02-02 12:26
My Environment：
Windows 10
OpenBLAS-v0.2.14-Win64-int32
openfst
vs2017

Is it caused by openblas? @danpovey

**Comment by danpovey** [comment] 2020-02-02 12:30
It's hard to say... actually if wav-copy has the same issue it's unlikely
to be BLAS-related.
Of course if you made any code changes let us know.
To debug this it would be helpful to try to read and write the same file on
Windows and Linux, and add print statements to see whether at least the
reading produces consistent results.  And you could inspect the output of
wav-copy with `od -c` (well, after transferring to Linux so that command
would exist) to see whether it seems to be byte-swapped.

**Comment by 111Moderato** [comment] 2020-02-02 12:38
1. The same command runs normally in centos7. The output wav file is a segment of speech voice, not noise.
2. No additional changes to the code.
3. One difference is : in CentOS I use MKL, while in windows I use openblas.

**Comment by 111Moderato** [comment] 2020-02-03 14:42
![image](https://user-images.githubusercontent.com/28188655/73661373-ea87c980-46d4-11ea-8b6f-8970255699f1.png)
 I found that function **WaveData::Write** causes this problem :
https://github.com/kaldi-asr/kaldi/blob/98f2edfeb7c6b6efab42d0ab48cff070f37ca363/src/feat/wave-reader.cc#L375

But I don't understand the difference of “ostream” between windows and Linux?  Do you know how to solve it? @danpovey

**Comment by danpovey** [comment] 2020-02-03 15:14
I don't know what the problem is, you just showed a line of code.
ostream should be the same in this respect.
I'd need to know what the difference in the output files (from wav-copy)
is.  You could perhaps test the difference by doing `diff` or `cmp`.

**Comment by kkm000** [comment] 2020-07-17 12:21
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Closed by kkm000** 2020-07-17 12:21 UTC
Labels: bug
