### ISSUE TITLE
mkl.h no such file and SSIZE_t redefinition in types.h

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#3683] opened 2019-10-25 06:12 UTC
I am facing these issues:
1) mkl.h: no such file or directory (whereas I am using openBLAS)
2) SSIZE_t redefintion in types.h
Kindly help me resolve these issues.
![mkl](https://user-images.githubusercontent.com/51845054/67547344-4c20bb00-f718-11e9-95d2-235f861a4b2e.PNG)
![ssize_t](https://user-images.githubusercontent.com/51845054/67547345-4cb95180-f718-11e9-8aa8-7ec3a32b3aad.PNG)

**Comment by Momina12** [comment] 2019-10-25 06:54
I am building the kaldi solution file for windows created by vs2017.

**Comment by kkm000** [comment] 2019-10-30 01:06
You need to provide more information. Also, please do not post pictures: they unreadable and very uninformative. Switch to the Output window, select Build, and copy an entire line of the error.

> I am building the kaldi solution file for windows created by vs2017.

What do you mean by this? How exactly did you create them?

> I am using openBLAS

Unless you have a _very specific_ reason not to, the best option for Windows is MKL. It's freely available from Intel, and its installer integrates it into Visual Studio very well. If you must use OpenBLAS, check the include file `src/kaldi-math.h` and figure out how to define suitable macros. You have the macro `HAVE_MKL` defined in your project files, and it does `#include <mkl.h>` under this condition.

The "type redefinition" error is most likely caused by missing include guards in some file. Since we are very careful about it, the most likely source is one of your OpenBLAS files. These are tricky to find; see the compiler's help (`cl /help` from the build environment console window), and have the compiler print the tree of include files as it preprocesses them. That's a lot of noise, but sure way to find it.

Also (I'm repeating myself) check the Output window, Build subselector. Sometimes the compiler helps you with notes invisible in this error list, like "while compiling x.h included from y.h included from z.cc". This immediately tells you which file is missing the include fences in x.h. You may need to tweak compiler diagnostics options though so it shows this; I just do not remember.

**Comment by jmanf** [comment] 2020-03-11 07:53
2. SSIZE_t redefintion in types.h

There is likely unmatched build platform between OpenFST and Kaldi.
You'd better to check and make same build platform(x86/x64) in build configuration.

**Comment by kkm000** [comment] 2020-06-24 15:11
Are you using openfst from https://github.com/kkm000/openfst? Building for 32 or 64 bit?

The files in `windows/` generating VS projects can be wonky.

Can you check the full compiler output message in the Output window, not the Errors window? It has much more information.

**Comment by kkm000** [comment] 2020-07-21 21:03
I am closing this issue for now, as I'm receiving no feedback from you. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Closed by kkm000** 2020-07-21 21:03 UTC
Labels: question
