### ISSUE TITLE
aishell2 run.sh

### ISSUE THREAD

**Issue by bamba518** [kaldi-asr/kaldi#2532] opened 2018-07-04 08:37 UTC
when I run aishell2 like i run any other script ./run.sh everything works fine until
# GMM
if [ $stage -le 2 ]; then
  local/run_gmm.sh --nj $nj --stage $gmm_stage
fi
it just prints to screen
local/prepare_all.sh succeeded
+ nj=20
+ stage=1
+ . ./cmd.sh
++ export train_cmd=run.pl
++ train_cmd=run.pl
++ export decode_cmd=run.pl
++ decode_cmd=run.pl
++ export mkgraph_cmd=run.pl
++ mkgraph_cmd=run.pl
+ '[' -f ./path.sh ']'

**Comment by bamba518** [comment] 2018-07-04 09:12
if I comment this out, then it works
set -euxo pipefail
to  
#set -euxo pipefail

**Comment by dophist** [comment] 2018-07-04 12:57
@underdogliu  I couldn't reproduce any error on my Mac, could you please look into this?

**Comment by naxingyu** [comment] 2018-07-05 06:42
According to our investigation, a majority of Chinese Kaldi users do not
have GridEngine in hand.
That's why we choose run.pl as default, other than following the common egs
style.
I think a solution would be to warn the user that run.pl will consume a lot
of training time.

**Comment by danpovey** [comment] 2018-07-05 06:48
Please just do as I asked.

**Comment by GaofengCheng** [comment] 2018-07-05 06:51
SGE can be setup even though only one server is available.
And even though we have one server at hand, we will first setup a one-server SGE and run kaldi....

**Comment by dophist** [comment] 2018-07-14 07:58
@danpovey I think this issue has already been fixed in @underdogliu 's latest commit, time to close maybe.

**Closed** 2018-07-14 18:55 UTC
