### ISSUE TITLE
aishell2 online decoding

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2801] opened 2018-10-24 19:39 UTC
@underdogliu @naxingyu @dophist:

Can someone please add an online decoding example to the aishell2 setup and verify that it works?  Someone on the list is asking about this.
See here https://groups.google.com/d/msgid/kaldi-help/e5811b1c-bd5d-430f-a8a4-bbebe820c1bc%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by danpovey** [comment] 2018-10-24 19:49
turns out he was asking about the original aishell.  Not sure if that is different.  If you could do both it would be great, but either is OK.

**Comment by naxingyu** [comment] 2018-10-26 02:43
@danpovey Neither aishell nor aishell2 provided an online pitch setup. This is actually the reason we didn't use pitch when we committed the aishell2 example in the first place. It was designed for supporting online decoding on par with offline. But I can add online setup to aishell, so that people can migrate it to aishell2 easily.

**Comment by danpovey** [comment] 2018-10-26 02:46
Thanks.
If you have time, play with those options I mentioned, e.g. I'd be
interesting to see whether reducing the normalization-right-context from 75
to 25 will change the WER.
Dan

**Comment by naxingyu** [comment] 2018-10-26 02:52
OK.

**Comment by naxingyu** [comment] 2018-11-14 04:30
This issue is addressed.

**Closed** 2018-11-14 04:34 UTC
