### ISSUE TITLE
The larger arpa, the worse recognition!

### ISSUE THREAD

**Issue by muenraisi** [kaldi-asr/kaldi#2899] opened 2018-12-05 12:50 UTC
By comparing the latest and an older version way of building grammar file G.fst, I found that the latest version reduce the recognition rate for a large size arpa file (~10 Gb). The rate reduction is from ~70% to ~65% from a over 50 hours audio test.

The older way:
```
grep -v '<s> <s>' | grep -v '</s> <s>' | grep -v '</s> </s>' | arpa2fst - | fstprint |
    scripts/remove_oovs.pl oovs.txt | scripts/eps2disambig.pl | scripts/s2eps.pl | 
    fstcompile --isymbols=words.txt --osymbols=words.txt --keep_isymbols=false --keep_osymbols=false | 
   fstrmepsilon > G.fst
```
The latest way:
```
arpa2fst --disambig-symbol=#0 --read-symbol-table=data/words.txt - data/G.fst
```
We perform the comparison by decode the HCLG.fst made with kaldi/egs/wsj/s5/utils/mkgraph.sh. During the comparision, all of the other input file and parameters are kept the same except the way of building G.fst from arpa file. The arpa file is adjused from 10Mb to 10Gb by prunned from the same arpa file. For small size arpa file ( <100Mb), the recognition result for the older and the latest one almost the same. For middle size arpa file ( 100Mb -1Gb), there is only sligthly differece. For large size arpa file (~10Gb), the latest way has a very poor performance. 

We also perform the comparsion of G.fst directly by replacing as a biglm in decoding, the decoding result is almost the same whatever the arpa file size they build from. Thus, the latest way buidling G.fst is likely to be incompatible with the script kaldi/egs/wsj/s5/utils/mkgraph.sh for large size arpa file. 

Does anyone kwon why or encounter the same issue?

**Comment by danpovey** [comment] 2018-12-05 17:44
Can you show some kind of output that would let me know what version you
are using?  It would be printed out in log messages.

you could also send me, separately (dpovey@gmail.com), an archive that
contains the language model and the words.txt.  That should  allow me to
debug it.  The G.fst should be equivalent, so it should not be necessary to
go all the way to the HCLG.fst stage in order to debug it.

**Comment by muenraisi** [comment] 2018-12-06 11:54
@danpovey, Thanks for your reply!
The version I using is 5.4 for Kaldi and is 1.6.5 for the Openfst. 

I have checked that the G.fst are indeed equivalent in arc weights. However, the  final HCLG.fst are not strictly equivalent in arc weights with slightly differences. The fstequivalent tool also shows that for the final HCLG.fst the total weight of randomly selected arcs can be as large as 1%. By tracking the steps making HCLG, I found the initial difference in arc weight has occured in the step "fstdeterminizestar --use-log=true" after "fsttablecompose $lang/L_disambig.fst $lang/G.fst“. I am not sure wheather the slight difference made by fstdeterminizestar has any effect on the final decode.

Due to the company security, sorry to tell you that I am not alowed to send you the arpa file. Yet, I am trying to repeat the same issue in an open source lm arpa file.  When the preparation is complete. I would like to tell you as soon as possible.

**Comment by danpovey** [comment] 2018-12-06 22:24
Maybe the difference is actually in your lexicon, e.g. it has to do with
pronunciation probabilities or silence probabilities or something like
that.  Check where you got the lexicon from.

I am assuming there must be other differences in the how HCLG.fst was made,
e.g maybe a different script, or a different lang/ directory with different
lexicon?

Dan

**Comment by muenraisi** [comment] 2018-12-07 07:12
I run the same mkgraph script in the same machine based on the same lang directory excepted for the replaced G.fst. Besides, I also executed each command in the mkgraph manually to repeat the result and compared md5sum value to ensure that the same file used. I am wondering wheather the lack of states, due to the function RemoveRedundantStates in arpa2fst, brings the difference in determinizing the fst composed by L_disambig.fst and G.fst.

**Comment by danpovey** [comment] 2018-12-07 18:36
Hm.  Look at the line where it says "Overall log-prob per frame" or
whatever in the decoding-- is it more positive or more negative with the
newer graph?
And what kind of smoothing did you use for the LM?

Dan

**Comment by danpovey** [comment] 2018-12-07 19:07
Also let me know whether the final HCLG.fst was bigger with one or the
other G.fst.

**Comment by muenraisi** [comment] 2018-12-10 12:31
1. It is hardly to judge wheather the newer graph moer positive or more negative. Here is the detail difference in LG.fst and HCLG.fst, by tracking the transitions from the start state. 

For LG.fst, left is newer , right is older. (As an example, the 2th and 4th line shows small difference, while the 3th line shows the same.)
Format: input label: outputstate, weight, nextstate| outputstate, weight, nextstate
 1  Start compare from 0 and 0.                                                                   
 2 216 : 0, 4.3779297, 79  | 0, 4.3769531, 80
 3 169 : 7686, 12.268555, 1160646  | 7686, 12.268555, 137524798
 4 41  : 0, 8.6298828, 42416906    | 0, 0.69628906, 25736980   -> 0, 7.8164062, 25736997
 5 291 : 3101, 0.24804688, 2344975 | 3101, 0.36914062, 5364486
 6 35  : 0, 8.15625, 789303    | 0, 8.125, 1449920
 7 62  : 4165, 2.2636719, 53730538 | 4165, 2.2949219, 116835524
 8 23  : 0, 0, 53730540    | 0, 0, 116835526
 9 290 : 0, 0, 53730118    | 0, 0, 116834831
10 1   : 0, 0.69335938, 53730119   | 0, 0.69335938, 116834832
11 348 : 0, 0, 53730120    | 0, 0, 116834834
12 101 : 221268, 3.4072266, 16235599   | 221268, 3.4072266, 116834833
13 252 : 0, 0, 54129898    | 0, 0, 116493575
14 291 : 0, 0, 16235601    | 0, 0, 116493576
15 98  : 148411, 2.3095703, 238559 | 148411, 2.3095703, 78248233
16 76  : 0, 0.69335938, 4716381    | 0, 0.69335938, 78248234
17 290 : 0, 0, 8981289 | 0, 0, 4768911
18 100 : 0, 6.6992188, 524676  | 0, 0.70703125, 1018885    -> 0, 5.7109375, 1018908
19 250 : 304142, 6.7246094, 7552058    | 304142, 7.0195312, 119494364
20 286 : 0, 0, 7552059 | 0, 0, 119494381
21 171 : 0, 0, 7552060 | 0, 0, 119494382


For HCLG.fst, left is newer , right is older.  (the difference can be seen from line 6 and 7, where the difference is no longer small )
Format: input label: outputstate, weight, nextstate| outputstate, weight, nextstate
 1  Start compare from 0 and 0.
 2 2972    : 0, 9.3203125, 245753973   | 0, 9.3203125, 306534704
 3 2971    : 0, 0.069314718, 245753973 | 0, 0.069314718, 306534704
 4 2971    : 0, 0.069314718, 245753973 | 0, 0.069314718, 306534704
 5 0   : 0, 0.069314718, 245753889 -> 1046 : 0, 2.7792969, 245725241   | 0, 0.069314718, 306534620 -> 0, 2.7792969, 306503234
 6 2   : 10054, 2.7304475, 239050766   | 10054, 3.4081819, 295961648
 7 5260    : 0, 7.8759556, 355124320   | 0, 7.1982212, 419241681
 8 5259    : 0, 0.069314718, 355124320 | 0, 0.069314718, 419241681
 9 5259    : 0, 0.069314718, 355124320 | 0, 0.069314718, 419241681
10 0   : 0, 0.069314718, 245725559 -> 3086 : 9604, 1.1708984, 658767   | 0, 0.069314718, 295961612 -> 9604, 1.1708984, 27774005
11 4322    : 0, 0.069314718, 658768    | 0, 0.069314718, 1950770
12 13678   : 0, 0.069314718, 658769    | 0, 0.069314718, 27774006
13 10062   : 0, 0.069314718, 658770    | 0, 0.069314718, 1950771
14 10061   : 0, 0.069314718, 658770    | 0, 0.069314718, 1950771
15 10061   : 0, 0.069314718, 658770    | 0, 0.069314718, 1950771
16 9090    : 0, 0.069314718, 247041781 | 0, 0.069314718, 309386318
17 9089    : 0, 0.069314718, 247041781 | 0, 0.069314718, 309386318
18 9089    : 0, 0.069314718, 247041781 | 0, 0.069314718, 309386318
19 9089    : 0, 0.069314718, 247041781 | 0, 0.069314718, 309386318
20 9089    : 0, 0.069314718, 247041781 | 0, 0.069314718, 309386318
21 0   : 0, 0.069314718, 658771    -> 15702    : 0, 5.1455078, 247041847   | 0, 0.069314718, 1950772   -> 0, 0.69335938, 534105    -> 0, 4.4521484, 307552906
22 0   : 0, 0.069314718, 24152045  -> 7994 : 0, 2.2910156, 154276278   | 0, 0.069314718, 1950787   -> 0, 2.2910156, 3024447
23 9178    : 453063, 3.510721, 1216299 | 453063, 3.510721, 3995048
24 8728    : 0, 0.069314718, 248059042 | 0, 0.069314718, 312026914
25 0   : 0, 0.069314718, 8703662   -> 4944 : 0, 4.9951172, 259523144   | 0, 0.069314718, 11019920  -> 0, 0.69335938, 369943    -> 0, 4.3017578, 307344090
26 0   : 0, 0.069314718, 383131    -> 3518 : 0, 4.4833984, 184411772   | 0, 0.069314718, 369956    -> 0, 4.4833984, 262379582                                                                          

2. The LM arpa file was formed by merging the daughter LMs with the " -interpolate -kndiscount" option in SRILM package.

3. The newer HCLG.fst is smaller as the newer G.fst is smaller. Here is the size as an example form the HCLG from 7G size arpa.
newer: G.fst(5.3G) -> LG.fst(3.0G) ->CLG.fst(3.3G) -> HCLG.fst(24G)
older: G.fst(12G) ->LG.fst(6.5G) -> CLG.fst(7.3G)-> HCLG.fst(29G)

**Comment by danpovey** [comment] 2018-12-10 17:07
If there are significant differences in the graphs, it will likely be for
selected paths, it won't be visible in a random path necessarily.
I was asking you for something else-- re-read what I said more carefully.
I suggest to rerun the interpolate command with a higher debug level so
SRILM will check that it's properly normalized.  Also check that '#0' is
not in the vocabulary of the LM.

Dan

**Comment by armusc** [comment] 2019-02-11 10:12
Hi

has this discussion landed somewhere then? I seem to observe something like this.
I have a 4-gram backoff LM (modified Kneser-Ney with SRI). I used this only for rescoring, it's the LM that provides the scores to add, while the LM used in decoding comes from a bigram.
It's not that large, about 1.4 GB.

I generate the corresponding G.fst with the "new" and and "old" method, the words.txt is the same.
In this last case the G.fst is much bigger, about 1.6GB against 0.9 GB with the new method (same command line reported in the messages above) 

If I test equivalence with random paths generated with fstequivalent, the two methods are different


When I rescore (with lattice-lmrescore-pruned) I go down from 16% wer (with no rescoring) to 14% with the old method, and I go up to 21% with the new method

**Comment by danpovey** [comment] 2019-02-11 18:02
It would be too much work for me to figure out what you mean.  Can you
please be much more specific about what you are comparing against what?

**Comment by armusc** [comment] 2019-02-11 18:42
I am comparing two different procedures for generating the LM fst in Kaldi, "old" and "new". 
old:
  #Get OOVS
  cat $lm | \
  find_arpa_oovs.pl $odir/words.txt > $tmpdir/oovs.txt

  #Get Kaldi LM FST
  
  cat $lm | \
  grep -v '<s> <s>' | grep -v '</s> <s>' | grep -v '</s> </s>' | \
  arpa2fst - | \
  fstprint | \
  remove_oovs.pl $tmpdir/oovs.txt | \
  eps2disambig.pl | \
  s2eps.pl | \
  fstcompile --isymbols=$odir/words.txt --osymbols=$odir/words.txt \
    --keep_isymbols=false --keep_osymbols=false | \
  fstrmepsilon \
    > $odir/$out.fst

new:
 cat $lm | arpa2fst --disambig-symbol=#0 --read-symbol-table=$odir/words.txt  - $odir/$out.fst


given the same $lm and $odir/words.txt  I got an fst of 1.6 GB with the old procedure and 0.9 GB with new one. The arpa file $lm is 1.4 GB of size.
When I used the two differents fst to rescore lattices I obtain different WER as well: 14% with the old fst, 21% the new one (which is worse than the WER I get with no 4-gram rescoring, 16%).
With respect to your previous suggestions, the LM does not contain the  "#0" in the vocabulary, though I have not rerun the LM estimation command with a higher debug level. I understand I have not added much with respect to my previous post, though, what would you need to know in addition?

**Comment by danpovey** [comment] 2019-02-11 18:50
If you can send me the files necessary to reproduce this, I may be able to
help debug.  Let me know where you got the LM from too

**Comment by danpovey** [comment] 2019-02-11 18:54
And also LMK what version of Kaldi code you have.

**Comment by armusc** [comment] 2019-02-12 13:46
Hi

I might have been identified where the problem comes from. Following your earlier suggestion on checking the normalization of the LM, I have realized interpolation by SRI binary ngram was done without the "-renorm" option. Adding this option, while the "new" fst is still smaller than the "old" one, results after rescoring are the same.
Any hint why would this make a difference in one case (with the new command) and not in the other (old command)?

**Comment by danpovey** [comment] 2019-02-12 14:45
Oh.
That's odd.   I should look into this.
Are these LMs heavily pruned?
There is a difference in how we treat backoff arcs in cases where the state
you are backing off to has no seen n-grams... basically, we skip over them
and go directly to the backed-off-to state.  So there is one backoff arc
instead of two or three.  (Those states still have backoff probs listed in
the arpa because they have to exist given how the ARPA format works, but
they don't really need to exist).  This only happens if the LM has been
pruned.
Dan

**Comment by armusc** [comment] 2019-02-12 14:52
the LM has been pruned with a factor 1e-9

**Comment by danpovey** [comment] 2019-02-12 14:57
See if you can identify states where the backoff prob changes the most, and
see if there are states with no n-grams (backoff prob exists but there are
no n-grams starting with that) and how much the backoff prob changes when
you recompute... it's odd because you would expect that backoff prob to be
1.0 (zero in the ARPA file) so that should not really change.

**Comment by armusc** [comment] 2019-02-12 18:53
I am embarrassed to say, but this looks like a false alarm; I did not do personally that LM and the corresponding fst (old and new, or at least, I did it myself today); but now I have redone everything and the two methods gives the same result (or almost the same, very slightly differences). as far as the -renorm option, that does not make any difference at all, as the LM, with or without, is identical
I apologize if I wasted your time, sorry

**Comment by danpovey** [comment] 2019-02-12 19:08
Oh OK, no problem.
I think the previous one turned out to be a false alarm too, but not 100%
too.

**Comment by danpovey** [comment] 2019-02-12 19:08
.. not 100% sure.

**Comment by armusc** [comment] 2019-02-13 11:42
it was just that, at the time it was done, (for some obscure reason), the
fst of the 4-gram was obtained from a words.txt that contained one less
word than words.txt used for the fst of the bi-gram (used in decoding); so
errors in rescoring were happening from where the mismatch was occurring
should have been the first thing to check

**Comment by kkm000** [comment] 2019-03-08 04:35
@armusc, FWIW, to me the `-renorm` made difference only when I rudely threw out a sizable bunch of lines from an existing ARPA LM file (I had a specific reason for that: there were special tokens that I could allow be only the last in any n-gram). It was never required when e. g. interpolating already well-normalized models etc. Inteprolation should preserve the normalized property in SRILM. So one of the input LMs could have been messed up, I suspect.

**Comment by kkm000** [comment] 2019-03-08 05:10
@danpovey 
> I think the previous one turned out to be a false alarm too, but not 100% [sure]

I am a little alarmed, too. I once rewrote the compiler from the ground up, and, while it passed all the tests, it's not impossible I introduced a tricky bug. The old and new FST were supposed to be equivalent (algebraically), but are not not identical as graphs. And @muenraisi exactly compares the old and the new compilers. 

But the provided info is not really enough. I'm not worried about different (byte) sizes of the resulting machines, as not only structural changes but even weight distribution along paths affect the composed machine file size. Also, I remember that I skipped outputting of many redundant epsilon arcs that were produced by the old compiler. So this is also rather a non-signal to me.

The RemveRedundantStates() seems benign at the first sight, too.

@muenraisi, do you have any new information? I understand LMs may be guarded by the company; I thought, no repro comes up except the one that bothers you, maybe you can share an anonymized version (replace words with numbers from words.txt, for example, or sha hashes, or something like that; please keep `<s>` and `</s>`, naturally).

**Comment by armusc** [comment] 2019-03-08 07:20
it was just a mismatch between the word symbol table of the bigram FST
(used in decoding) and the 4gram, used for rescoring; it was not related to
the language models

**Closed** 2019-03-31 10:30 UTC

**Comment by v-yunbin** [comment] 2021-02-28 01:20
whether have some commands coverting HCLG.fst to G.fst？

**Comment by danpovey** [comment] 2021-02-28 03:44
That can't really be done.
In principle you might be able to do it by deleting the ilabels and removing epsilons, but I think it would blow it up enormously and might change the weights.

**Comment by wwfcnu** [comment] 2023-04-13 09:47
fsttablecompose L.fst G.fst 这一步需要多少内存啊，30G的fst在125G内存的机器上都跑不起来
