### ISSUE TITLE
Change OnlineNnet2FeaturePipeline to OnlineFeatureInterface in SingleUtteranceNnet3Decoder

### ISSUE THREAD

**Issue by achernetsov** [kaldi-asr/kaldi#1925] opened 2017-10-08 09:45 UTC
The goal: to support OnlineFeaturePipeline for tdnn decoding.

Sorry, I'm new to kaldi, here is story, why I make this suggestion:
In Russian community tdnn model was shared, trained without ivector.  Online decoding works, if change OnlineNnet2FeaturePipeline to OnlineFeaturePipeline.

SingleUtteranceNnet3Decoder has dependency on OnlineNnet2FeaturePipeline, because it instantiate _decodable with ivector (but ivector can be NULL and OnlineFeaturePipeline will work).

I implemented this in https://github.com/achernetsov/kaldi/tree/tdnn-online-feature-pipeline, but this is ad-hoc solution and will work only without ivector.

**Comment by danpovey** [comment] 2017-10-08 17:14
I'm pretty sure this is already supported.  See what kinds of configs
prepare_online_decoding.sh gives you if you provide no ivector-related
options or arguments.

**Comment by achernetsov** [comment] 2017-10-09 18:54
I tried, it running without errors, but recognition with OnlineNnet2FeaturePipeline without ivectors for this specific model is wrong, while with OnlineFeaturePipeline is correct.

I also watch commit history for SingleUtteranceNnet3Decoder and in [47b7a6b5c755220b36d1f86176ca3fc60df9b0e6]( https://github.com/kaldi-asr/kaldi/commit/47b7a6b5c755220b36d1f86176ca3fc60df9b0e6) it was changed to OnlineFeatureInterface (by author of this russian model), and later in [16afe7ae7e69080f723b4ce5072f58a94c19e00c](https://github.com/kaldi-asr/kaldi/commit/16afe7ae7e69080f723b4ce5072f58a94c19e00c) you changed it again on OnlineNnet2FeaturePipeline

Actually, this is not big deal, I always can implement new Decoder for this specific case, but this looks strange. If both pipeline supported, why interface changed to impementation here.

**Comment by danpovey** [comment] 2017-10-09 19:04
How wrong is it?  Probably there was some configuration value that you failed to pass in.
Were you able to figure out how to pass in all the configuration values that you previously were passing to OnlineFeaturePipeline, into OnlineNnet2FeaturePipeline?

**Comment by danpovey** [comment] 2017-10-09 19:07
BTW, it might be possible to implement what you want using an alternative
constructor and changing some other aspects of the class (e.g. the type of
the pointers it holds).

But currently it should just work.  That is, if you train a model without
ivectors, and create the configs using prepare_online_decoding.sh (without
ivector-related arguments), it should give you a config file that will
allow you to decode correctly.  So as far as I can see there is no real
need to change the code.  Nickolay, if he still has the original models,
may be able to figure out the appropriate config files.

If there is a bug I will fix it, but I doubt that.

**Comment by achernetsov** [comment] 2017-10-09 19:10
@danpovey thank you for support! 
I will dig in and will try to solve this.

**Comment by nshmyrev** [comment] 2017-10-09 21:53
Hi Dan. I think the issue is that the model is trained with online cmn and without ivector and nnet2 pipeline does not support online cmn in features, only inside ivectors. Anyway, I think we can close this issue, I'll just share the next model iteration with small dimension ivector, so the model will be compatible with the latest pipeline.

**Comment by danpovey** [comment] 2017-10-09 21:54
OK, cool.
Was the online cmn helpful-- did you try without it?
Dan

**Comment by nshmyrev** [comment] 2017-10-09 22:01
Great idea, I didn't try yet, but I'll try. Thank you!

**Comment by achernetsov** [comment] 2017-10-09 22:07
I think pipeline should fail fast, if someone try to use it with model not supposed to be used with pipeline

**Comment by danpovey** [comment] 2017-10-09 22:10
Artyom-- the models are generic, they don't come with information about
what features they were built for (other than dimension) and adding that
would require a major redesign of a lot of things,which would also have
downsides.

**Closed** 2017-10-09 22:15 UTC
