### ISSUE TITLE
Meet an error when making /src

### ISSUE THREAD

**Issue by ForNovsta** [kaldi-asr/kaldi#4748] opened 2022-05-26 06:07 UTC
I am a starter for kaldi and was installing kaldi on my virtual machine with ubuntu-20.04.2.0 system and met an error when making the /src. The report is 

![image](https://user-images.githubusercontent.com/75245033/170425968-04241f7e-8fd7-4fd2-a245-279b8ae0d70a.png)

(没有那个文件或目录 = no such file or dictionary, 错误 = error)

It seems like I am lack of a file called libkaldi-online2.so, but I searched it and cannot find it anywhere in my virtual machine. I followed the instructions written in INSTALL documents, everything went fine until this error was raised. What should I do to deal with this? Thanks for everyone who helps me.

**Comment by jtrmal** [comment] 2022-05-26 11:51
there was probably some error before tihs error
y.

**Comment by ForNovsta** [comment] 2022-05-26 12:14
That's so bad. Is this error related to the make of /tools since it is complated before making /src? Or just something went wrong when making /src? Would it help if I remake it?

**Comment by csukuangfj** [comment] 2022-05-26 12:17
I would recommend you to post the commands you used and also post more logs to give us a better context.

**Comment by ForNovsta** [comment] 2022-05-26 12:39
Well unfortunately I have closed the terminal and don't know how to find the logs back, but I can tell you the commands I used if it helps.
Firstly I used `git clone https://github.com/kaldi-asr/kaldi.git` 
Then I went kaldi/tools and ran `extras/check_dependencies.sh` and it reported that I am ready to make tools, then I used command `make` and waiting for several hours until it reported all done.
Then I went kaldi/src and use `./configure --shared` and it said I am ready to make src. As it instructed I used command `make depend`, after it was over, I used command `make` and waiting for another several hours until the error I have posted was raised.
I am going to remake the src if the report logs really matters and after several hours I could post the logs here.

> I would recommend you to post the commands you used and also post more logs to give us a better context.

**Comment by csukuangfj** [comment] 2022-05-26 12:41
If you have several CPU cores, e.g, 8 cores, you can use
```
make -j 8
```
to reduce the compilation time.

**Comment by jtrmal** [comment] 2022-05-26 12:42
this will cause the error to be buried somewhere where I'm not confident
they will be able to find it.

**Comment by jtrmal** [comment] 2022-05-26 12:42
I had a good reason to suggest -j 1
y.

**Comment by ForNovsta** [comment] 2022-05-26 12:43
The virtual machine only provides one CPU, so I could not use this method to accelerate :-(

> If you have several CPU cores, e.g, 8 cores, you can use
> 
> ```
> make -j 8
> ```
> 
> to reduce the compilation time.

**Comment by ForNovsta** [comment] 2022-05-26 12:47
Did the commands I have used have something unproper?  The make of /src takes really long time, so if something besides it went wrong please tell me so I can repair it now.

**Comment by csukuangfj** [comment] 2022-05-26 12:48
You can use
```
make -j1 2>&1 | tee make-log.txt
```
and post `make-log.txt`.

No. Your commands look OK, I think.

**Comment by ForNovsta** [comment] 2022-05-26 17:05
After several hours' make, finally it  #ended with the same error and here is the log,
[make-log.txt](https://github.com/kaldi-asr/kaldi/files/8780642/make-log.txt)
 Hope it could say something that helps.


> You can use
> 
> ```
> make -j1 2>&1 | tee make-log.txt
> ```
> 
> and post `make-log.txt`.
> 
> No. Your commands look OK, I think.

**Comment by csukuangfj** [comment] 2022-05-27 01:48
I confirm that the issue is reproducible, which is introduced by #4744, I think.

That PR removes the following lines from `src/Makefile`:
```
# this is necessary for correct parallel compilation
#1) The tools depend on all the libraries (which is a nonsense)
bin chainbin featbin fgmmbin fstbin gmmbin ivectorbin \
    kwsbin latbin lmbin nnet2bin nnet3bin nnetbin online2bin rnnlmbin : \
 $(BMU) chain cudamatrix decoder feat fstext gmm hmm ivector \
        kws lat lm nnet nnet2 nnet3 online2 rnnlm transform tree
```
which is the cause of this issue.

#4637 added `online2` as a dependency for `nnet3bin` but #4744 removes it.

Should be fixed by #4749

**Comment by ForNovsta** [comment] 2022-05-27 01:56
Thanks a lot, and should I redo the whole installation process or just fix the src/Makefile?

> I confirm that the issue is reproducible, which is introduced by #4744, I think.
> 
> That PR removes the following lines from `src/Makefile`:
> 
> ```
> # this is necessary for correct parallel compilation
> #1) The tools depend on all the libraries (which is a nonsense)
> bin chainbin featbin fgmmbin fstbin gmmbin ivectorbin \
>     kwsbin latbin lmbin nnet2bin nnet3bin nnetbin online2bin rnnlmbin : \
>  $(BMU) chain cudamatrix decoder feat fstext gmm hmm ivector \
>         kws lat lm nnet nnet2 nnet3 online2 rnnlm transform tree
> ```
> 
> which is the cause of this issue.
> 
> #4637 added `online2` as a dependency for `nnet3bin` but #4744 removes it.
> 
> Should be fixed by #4749

**Comment by csukuangfj** [comment] 2022-05-27 01:58
> Thanks a lot, and should I redo the whole installation process or just fix the src/Makefile?

Just fix the Makefile should work. No need to clean&make

**Comment by ForNovsta** [comment] 2022-05-27 02:06
Well, then how should I fix the Makefile, should I insert your code to somewhere in the file? Or replace something?

> > Thanks a lot, and should I redo the whole installation process or just fix the src/Makefile?
> 
> Just fix the Makefile should work. No need to clean&make

**Comment by csukuangfj** [comment] 2022-05-27 02:13
Just replace
https://github.com/kaldi-asr/kaldi/blob/1a233a11db0b28aa4966a4e271c839c135de5914/src/Makefile#L191
with
https://github.com/kaldi-asr/kaldi/blob/c8d91148eb31eba191c89c16862532ba12b36eb8/src/Makefile#L191

**Comment by ForNovsta** [comment] 2022-05-27 02:15
Get it. I would report if I were successful or not as soon as the result come out.

> Just replace
> 
> https://github.com/kaldi-asr/kaldi/blob/1a233a11db0b28aa4966a4e271c839c135de5914/src/Makefile#L191
> 
> 
> with
> https://github.com/kaldi-asr/kaldi/blob/c8d91148eb31eba191c89c16862532ba12b36eb8/src/Makefile#L191

**Comment by ForNovsta** [comment] 2022-05-27 02:37
With the fix the make is successful, thanks.

**Closed** 2022-05-27 02:38 UTC
Labels: bug

**Comment by jtrmal** [comment] 2022-10-11 07:59
no, probably in the src make...
just run `make -j 1` again -- the `-j 1` is important in this case
y.
