### ISSUE TITLE
remove 'ar' option

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2415] opened 2018-05-11 22:44 UTC
@jtrmal, what do you think..
when linking I'm getting these warnings:

ar -cru kaldi-nnet3.a nnet-common.o nnet-compile.o nnet-component-itf.o nnet-simple-component.o nnet-normalize-component.o nnet-general-compone\
nt.o nnet-parse.o natural-gradient-online.o nnet-descriptor.o nnet-optimize.o nnet-computation.o nnet-computation-graph.o nnet-graph.o am-nnet-\
simple.o nnet-example.o nnet-nnet.o nnet-compile-utils.o nnet-utils.o nnet-compute.o nnet-test-utils.o nnet-analyze.o nnet-example-utils.o nnet\
-training.o nnet-diagnostics.o nnet-am-decodable-simple.o nnet-optimize-utils.o nnet-chain-example.o nnet-chain-training.o nnet-chain-diagnosti\
cs.o discriminative-supervision.o nnet-discriminative-example.o nnet-discriminative-diagnostics.o discriminative-training.o nnet-discriminative\
-training.o nnet-compile-looped.o decodable-simple-looped.o decodable-online-looped.o convolution.o nnet-convolutional-component.o attention.o \
nnet-attention-component.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib kaldi-nnet3.a

This seems to come from makefiles/default_rules.mk, where 'ar -cru' is used.  I wonder if the 'u' option is unnecessary?

**Comment by galv** [comment] 2018-05-15 16:30
`-u` will "update" the archive with only those .o files listed on the command line that are newer than those same-named .o files in the .a file. But because `-D` is on by default, the timestamp on the .o files inside the .a file are forced to 0 (beginning of unix time. 1970 or whatever?). So you will basically always update all files in the archive, making the `-u`option pointless.

I looked into this once a long time ago, but never made an issue for it.

**Comment by jtrmal** [comment] 2018-06-08 12:53
I didn't notice this -- will try to update the switches -- but I wonder if this will cause troubles for older ar releases, as I didn't see this message until very recently?

**Comment by jtrmal** [comment] 2018-06-09 12:37
Seems to be related to this:
https://wiki.debian.org/ReproducibleBuilds/TimestampsInStaticLibraries
I propose to do as @danpovey suggests -- to remove the u option. Another possibility would be to add U option, which (at least that is my impression) would revert us to the old behavior. The library creation would be a bit faster, but I don't think this is the bottleneck in compilation with static libs.

**Comment by jtrmal** [comment] 2018-06-13 14:45
resolved, closing

**Closed by jtrmal** 2018-06-13 14:45 UTC
