### ISSUE TITLE
Chime4 egs

### ISSUE THREAD

**Issue by kobayakawa-t-ko** [kaldi-asr/kaldi#2793] opened 2018-10-17 01:35 UTC
It seems chime4 egs has the following problems.
1. The latest miniconda is not working.
2. matlab is required to generate data.

As for 1, since current chainer is not working with python3.7, I use the following fix.
Maybe this fix is for the time being. (i.e. temporal fix)

<pre>
--- a/tools/extras/install_miniconda.sh
+++ b/tools/extras/install_miniconda.sh
@@ -4,8 +4,9 @@
 # Miniconda will be installed in the HOME directory. ($HOME/miniconda3).
 # Also don't make miniconda's python as default.
 
-wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
-bash Miniconda3-latest-Linux-x86_64.sh -b
+miniconda_shell=Miniconda3-4.5.4-Linux-x86_64.sh
+wget https://repo.continuum.io/miniconda/$miniconda_shell
+bash $miniconda_shell -b
 
 $HOME/miniconda3/bin/python -m pip install --user tqdm
 $HOME/miniconda3/bin/python -m pip install --user scikit-learn
</pre>

As for 2, I would be nice to be considered the possibility of free replacement(such as octave).

**Comment by galv** [comment] 2018-10-23 07:31
What is wrong with the latest miniconda install? If it is intermittent (a bad build was pushed by the conda people), I don't think we should lock the recipe to an old version of miniconda. If the problem is that it uses python3.7, the reality is that this recipe should create a custom environment with a locked version of python. e.g.:

`conda create -n chime4env python=3.6`

Regarding the matlab thing, someone would need to be willing to adapt the existing matlab code to be octave compatible.

**Comment by kobayakawa-t-ko** [comment] 2018-10-24 01:53
Yes, chainer is not working with python3.7 yet, as there is an issue:
https://github.com/chainer/chainer/issues/5109

**Comment by kkm000** [comment] 2019-03-31 10:37
I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.

**Closed by kkm000** 2019-03-31 10:37 UTC
