### ISSUE TITLE
Not all Kaldi libs is compiled for Android

### ISSUE THREAD

**Issue by vgritsko** [kaldi-asr/kaldi#4280] opened 2020-09-23 10:31 UTC
Hello!
I'm trying to compile Kaldi for Android. I use NDK 21.3. But it's seems not all libs is compiled from Kaldi. I see only : 

1. ibkaldi-base.so
2. libkaldi-cudamatrix.so
3. libkaldi-feat.so
4. libkaldi-gmm.so
5. libkaldi-ivector.so
6. libkaldi-lm.so
7. libkaldi-nnet2.so
8. libkaldi-online2.so
9. libkaldi-tree.so
10. libkaldi-chain.so
11. libkaldi-decoder.so
12. libkaldi-fstext.so
13. libkaldi-hmm.so
14. libkaldi-lat.so
15. libkaldi-matrix.so
16. libkaldi-nnet3.so
17. libkaldi-transform.so
18. libkaldi-util.so

There are no any errors  when is compiling.
But why next libs is not compiled:
libkaldi-nnet.so
libkaldi-online.so
libkaldi-kws.so

Thanks.

**Comment by danpovey** [comment] 2020-09-23 10:48
I have no idea,
I'd first look and see if there's anything different about their Makefiles,
or references to their makefiles in src/.  There doesn't seem to be though.
at least in current checked-in kaldi.

**Comment by nshmyrev** [comment] 2020-09-23 10:50
I believe it is a duplicate of https://github.com/alphacep/vosk-api/issues/225, not really relevant to kaldi

**Comment by vgritsko** [comment] 2020-09-23 11:08
> I believe it is a duplicate of [alphacep/vosk-api#225](https://github.com/alphacep/vosk-api/issues/225), not really relevant to kaldi

I clone Kaldi from this repository but have the same libs as Vosk-Api.

**Comment by kkm000** [comment] 2021-04-25 06:13
@vgritsko, did you find a workaround?

**Comment by kkm000** [comment] 2021-05-12 07:59
Thanks. I think it's not an issue at the moment, haven't heard of it since. I'm closing this. We can go back to it if it resurfaces.

**Closed by kkm000** 2021-05-12 07:59 UTC
