### ISSUE TITLE
Issue In kaldi/egs/ami/s5/local/ami_download.sh

### ISSUE THREAD

**Issue by ervaibhavkumar** [kaldi-asr/kaldi#2766] opened 2018-10-07 04:47 UTC
Hi,

I have found issue in the file fetched by command wget in the file kaldi/egs/ami/s5/local/ami_download.sh
I would like to work on it .
Can i start on this ?

Regards
Vaibhav

**Comment by danpovey** [comment] 2018-10-07 05:01
Sure, but let us know what the issue is first.  It might just be a firewall
problem.

**Comment by puneetbawa** [comment] 2018-10-08 08:17
The URL was pointing to file which doesn't exist . I had resolved in in #2769

**Comment by ervaibhavkumar** [comment] 2018-10-08 17:12
@puneetbawa I think these resolves the issue 👍

**Closed** 2018-10-16 11:41 UTC
