### ISSUE TITLE
Failed to copy prob file

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#3680] opened 2019-10-24 05:55 UTC
I am compiling kaldi on windows.  I am running 
perl generate_solution.pl --vsver vs2017 --enable-openblas
Issue is: ERROR: failed to copy prop file C:/Users/user_name/kaldi/windows/variables.props
I have checked variables.props already exists in this folder. I am sharing screenshots for your assistance.
Kindly help me to resolve this issue

**Comment by danpovey** [comment] 2019-10-24 06:07
This is a duplicate of #3677.  The answer will not change by asking again

**Closed by danpovey** 2019-10-24 06:07 UTC
Labels: discussion

**Comment by Momina12** [comment] 2019-10-24 06:18
No, its not duplicate. At #3677, I asked you at step#10 of windows/INSTALL. Now, i returned back to step#8 .i.e. I am creating MSVC solution file again by running generate_solution.pl script. 
Kindly have a look at the screenshots:
![Capture](https://user-images.githubusercontent.com/51845054/67458531-da7d3a00-f64f-11e9-84a3-1204b68f1f60.PNG)
![Screenshot (1)](https://user-images.githubusercontent.com/51845054/67458538-dea95780-f64f-11e9-8c9e-aa88f399da48.png)

**Comment by danpovey** [comment] 2019-10-24 06:48
Probably a permissions issue on variables.props (like the previous issue)
but I forget how to debug those on Windows.
You'll have to search.
