### ISSUE TITLE
maybe set CPPFLAGS="-stdlib=libstdc++" in tools/extras/install_sequitur.sh

### ISSUE THREAD

**Issue by jasonrayles-nbcuni** [kaldi-asr/kaldi#1107] opened 2016-10-11 20:14 UTC
When installing sequitur on OS X, I think that
`make CPPFLAGS="-stdlib=libstdc++"` is required.

This solution was proposed at https://groups.google.com/forum/#!msg/kaldi-help/x3AJzKHe5lY/EpBJORtFAgAJ. I am not sure what the implications of explicitly setting this option is for all users, but according to http://stackoverflow.com/a/16788372, libstdc++ is the standard GNU/Linux library, anyway. 

If nothing else, perhaps a comment in the install script will could save new users some time.

**Comment by jtrmal** [comment] 2016-10-11 20:23
Thanks for reporting it, I'll have a look.
MacOS is annoying as the default libc is clang's one (libc++) as far as I understand.  I will investigate, but do not expect a quick fix -- if you have enough technical experience, can you please add that flag just to see what happens?

Also, my feeling is it should go into CXXFLAGS, but perhaps that does not matter

**Comment by jasonrayles-nbcuni** [comment] 2016-10-11 20:34
` make CPPFLAGS="-stdlib=libstdc++" ` definitely works on OS X. I could not install sequitur without it.

**Comment by jtrmal** [comment] 2016-10-12 14:43
would you be willing to remove your sequitur and then change the extras/install_sequitur.sh so that the line 67 would say:
```
make CXX=g++ CC=gcc
```
My feeling is that is more correct solution anyway.

**Comment by jasonrayles-nbcuni** [comment] 2016-10-12 21:20
Ok, I just had a chance to try this. 

` make CXX=g++ CC=gcc ` did not work for me. 

I get
```
gcc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DMULTIGRAM_SIZE=4 -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c sequitur_wrap.cpp -o build/temp.macosx-10.11-intel-2.7/sequitur_wrap.o -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
In file included from sequitur_wrap.cpp:3148:
./Multigram.hh:37:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
make: *** [build] Error 1
```

I tried with variations of quotes and the full path to gcc on my system.

I also tried
` make CXXFLAGS="-stdlib=libstdc++" ` and got the same fatal error.

` make CPPFLAGS="-stdlib=libstdc++" ` is the only way I could get the install script to finish without errors.

**Comment by danpovey** [comment] 2016-10-12 21:21
What is your g++ version?

**Comment by jasonrayles-nbcuni** [comment] 2016-10-12 21:23
That is a good question.
` g++ --version ` gives me:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jtrmal** [comment] 2016-10-12 21:27
Yes, but that's clang's "imitation" of gcc -- it's not the real
gcc compiler. And apparently has issues with supporting anything later than
tr1.
Let me think if we can deal with that.

y.

**Comment by jtrmal** [comment] 2016-10-12 21:29
Does that "g++" compile kaldi?
y.

**Comment by jasonrayles-nbcuni** [comment] 2016-10-12 21:48
Yes.

**Comment by jtrmal** [comment] 2016-10-12 21:57
can you please send me the version of swig (swig -version)?

**Comment by jtrmal** [comment] 2016-10-12 22:00
And also the whole sequitur build log? I think it would be better, if you
send it directly to jtrmal _at_ gmail.com
The thing is I cannot reproduce your issues... It's actually even worse, I
can reproduce your issues but for a combination that works for you and you
report the issues for combination that work for me.
y.

**Comment by jtrmal** [comment] 2017-06-27 07:51
I'm still not able to reproduce this -- I'm adding a second attempt to compile things in case the previous make fails

**Comment by jtrmal** [comment] 2017-06-27 08:14
@jasonrayles-nbcuni I know it's been a long time but do you have time to test the #1716 if it addresses your issues?

**Comment by jasonrayles-nbcuni** [comment] 2017-06-27 14:50
I do not have access to an OS X machine at the moment, but I can test this in a couple of weeks. Sorry about that, and thank you for following up.

Jason

Sent from my iPad

On Jun 27, 2017, at 4:15 AM, jtrmal <notifications@github.com<mailto:notifications@github.com>> wrote:


@jasonrayles-nbcuni<https://github.com/jasonrayles-nbcuni> I know it's been a long time but do you have time to test the #1716<https://github.com/kaldi-asr/kaldi/pull/1716> if it addresses your issues?

-

**Comment by jtrmal** [comment] 2017-11-23 00:11
I'm closing this, as the patch is already checked in and we didn't head from anyone having issues

**Closed by jtrmal** 2017-11-23 00:11 UTC
