### ISSUE TITLE
Failing on wav-reverberate as --noise-file option is not there

### ISSUE THREAD

**Issue by bharathregula** [kaldi-asr/kaldi#1811] opened 2017-08-11 16:28 UTC
I am failing at this step of model training https://github.com/kaldi-asr/kaldi/blob/503e5ded49281a57c4b60bb53e4787100e35e0ce/egs/aspire/s5/local/nnet3/run_ivector_common.sh#L76
and the error I get in the log file is 

```
Command line was: wav-reverberate --noise-file=data/impulses_noises/RVB2014_type1_noise_largeroom1_6.wav --snr-db=0 - data/impulses_noises/RVB2014_type1_rir_largeroom1_near_anglb.wav - 
ERROR (wav-reverberate:Read():parse-options.cc:374) Invalid option --noise-file=data/impulses_noises/RVB2014_type1_noise_largeroom1_6.wav
```

I believe it is because wav-reverberate options has changed but it is not accounted at https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/reverberate_wavs.py#L88

**Comment by danpovey** [comment] 2017-08-11 18:08
@vijayaditya will know what to do.

**Comment by vijayaditya** [comment] 2017-08-11 23:35
reverberate_wavs.py is stale script. It should be deleted.

The issue is that the nnet3 scripts were not updated when the latest
reverberation recipe was added nnet2 scripts. Before this is rectified you
can copy over the data prep stage from nnet2 scripts here

https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/nnet3/run_ivector_common.sh#L26

**Comment by danpovey** [comment] 2017-08-11 23:36
@xiaohui-zhang, do you have time to fix these issues in the repo?

**Comment by xiaohui-zhang** [comment] 2017-08-12 03:17
sure. I can do it next week. is it ok?

**Comment by danpovey** [comment] 2017-08-12 04:08
sure.

**Comment by bharathregula** [comment] 2017-08-14 14:19
@vijayaditya if I understand you correctly, you want me to copy all the stage 1 steps of run_ivector_common from nnet2 scripts? If yes, then can you please point me where nnet2 scripts are located?

**Comment by vijayaditya** [comment] 2017-08-14 17:05
You can find it here

https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/run_nnet2_common.sh#L26

**Comment by bharathregula** [comment] 2017-08-14 20:20
Looks like run_nnet2_common.sh fails at this step: https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/run_nnet2_common.sh#L45 with error `reverberate_data_dir.py: error: argument --rir-set-parameters is required`. I checked reverberate_data_dir.py and it expects --rir-set-parameters which is missing in run_nnet2_common script

**Comment by vijayaditya** [comment] 2017-08-14 21:23
OK, finally found the issue. You seem to be on a branch and not the master.
When I checked the file you linked in your first mail :
your link :  https://github.com/kaldi-asr/kaldi/blob/
503e5ded49281a57c4b60bb53e4787100e35e0ce/egs/aspire/s5/
local/nnet3/run_ivector_common.sh#L76

the run_ivector_common.sh script did not have the latest changes with
reverberate_data_dir.py. I assumed you were on the master and recommended
to copy the recipe from nnet2.


However looking at the master branch I can see that run_ivector_common.sh
(master link:
https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/nnet3/run_ivector_common.sh#L26)
has the latest recipe.

@Samuel no need to update the recipe.

Please run the latest recipe from the master.


--Vijay

**Comment by danpovey** [comment] 2017-08-14 21:27
Closing the issue.  Check more carefully before opening an issue next time!

**Closed by danpovey** 2017-08-14 21:27 UTC
