### ISSUE TITLE
bug in steps/nnet3/decode.sh

### ISSUE THREAD

**Issue by osadj** [kaldi-asr/kaldi#1852] opened 2017-08-29 21:18 UTC
in steps/nnet3/decode.sh after the decoding, score.sh no longer accepts the iter option:

local/score.sh: invalid option --iter

**Comment by danpovey** [comment] 2017-08-29 21:24
It's not a bug in decode.sh, it's a bug in the local score.sh script.  It
should accept that option even if it is going to ignore it.
If that score.sh script is one checked into Kaldi, it would be great if you
could submit a fix.  It just needs to have a line

iter=final   #  The iteration of model to use (this is ignored but the
                 # option is passed in by some decoding scripts).

near the top where other options are declared.

**Comment by osadj** [comment] 2017-08-29 21:30
Sure, will do soon.

Regards,
Omid

**Comment by danpovey** [comment] 2017-08-29 21:50
Resolved in #1853

**Closed by danpovey** 2017-08-29 21:50 UTC
