### ISSUE TITLE
Issue with augment_data_dir.py

### ISSUE THREAD

**Issue by anderleich** [kaldi-asr/kaldi#3006] opened 2019-01-25 10:18 UTC
Hi all,
I'm trying to synthetically augment my training data by inserting background noises. However, when executing augment_data_dir.py for my own data following some of the examples in the recipes,  it is not working properly. This is the command I'm using:

`python steps/data/augment_data_dir.py --utt-suffix "music" --bg-snrs "15:10:8:5" --num-bg-noises "1" --bg-noise-dir "$MUSAN_DIR/musan_music" data/${PREFIX}_train_$LANG data/${PREFIX}_train_${LANG}_music`

This creates a data directory. Fixing this data directory with fix_data_dir.sh results in all utterances being removed. The wav.scp file looks like this:

`file1 wav-reverberate --shift-output=true --additive-signals='wav-reverberate --duration=8385.046 "sox -t wav reverberation/musan/speech/librivox/speech-librivox-0003.wav -r 16k -t wav - |" - |,wav-reverberate --duration=8385.046 "sox -t wav reverberation/musan/speech/librivox/speech-librivox-0031.wav -r 16k -t wav - |" - |' --start-times='0,0,0,0,0' --snrs='15,15,13,17,17' /audios/audio1.wav - |`

When I execute the piped command, in some cases it outputs an error about the volume of the audio. Is it possible that the volume is increasing to much due to the addition of new noises?

**Comment by david-ryan-snyder** [comment] 2019-02-27 14:57
You will probably want to use the script reverberate_data_dir.py (or the name is similar to that) instead. If you want to see usage of this script, look in the ASPIRE recipe. That script was designed with ASR in mind but conceptually it works similar to this one. This script, augment_data_dir.py was written for speaker recognition, and it has some quirks when being used for ASR.

**Comment by kkm000** [comment] 2019-03-08 22:30
> When I execute the piped command, in some cases it outputs an error about the volume of the audio.

SoX error message is sloppy at best; it's not about the *volume* (which is both the subjectively perceived characteristic of sound bite, and a semi-objective metric of audio, usually called "loudness", based on an empirical curve-weighted windowed RMS-power). The warning is about a point amplitude. Generally, just almost any DSP can introduce individual samples that overshoot the representable maximum, even on quiet audio.

On the practical side, if you see just a few of these errors, its totally safe to ignore them. One overshoot introduces just a little crackle at this point, and audio data is full of defects anyway. If you see multiple of these warning in nearly every file, then you may try to reduce amplitude by adding the `gain` filter to the SoX chain before processing. Go light, in -3dB steps. But again, do not overdo this. Lowering the amplitude equals increasing noise, due to amplitude quantization, and the noise will be amplified by future processing down the pipeline.

**Comment by kkm000** [comment] 2019-03-19 23:32
@anderleich, I'm closing this, feel free to ping if you believe the issue is not resolved.

**Closed by kkm000** 2019-03-19 23:32 UTC
