### ISSUE TITLE
Tune nnet3 LSTMs

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#134] opened 2015-09-13 18:06 UTC
I am creating an issue for this in case we can get wider help--
 Right now the thing that needs to be done that's most urgent for me is to get LSTMs tuned and working in the nnet3 setup.   I think at this point the essential code is all written and it's a question of tuning the scripts (e.g. adding more layers).  This is the limiting factor on me getting CTC working too (I'm doing it in a private branch, but I can't really test it until we have some recurrent setup working well).
  What I'd like done this this: @vijayaditya and @pegahgh, can you please (fairly urgently) make sure that the essential pieces of your work so far are checked in, and provide pointers to it here in this thread?  We can just check in the best configurations you have so far.  After that I am hoping others such as @naxingyu and @nichongjia will be able to help tune it using their setups.

**Comment by naxingyu** [comment] 2015-09-14 07:38
I'm happy to participate.

**Comment by nichongjia** [comment] 2015-09-14 08:09
Glad to do this.

**Comment by danpovey** [comment] 2015-09-14 18:35
Cool.   Vijay is making sure that stuff is checked in.  Vijay, please see
if there is anything that Pegah did in the interim which needs to be
checked in too.  She got some improvements out of label delay, I think.
Dan

**Comment by danpovey** [comment] 2015-09-14 21:50
OK, Pegah has checked in her latest changes.
Guys, you don't have to do this on AMI if it's not convenient-- just adapt the scripts to whatever setup is convenient for you.
Right now I am debugging some code which enables us to truncate the BPTT and not apply it to the left-context frames.  That should help both with speed and avoiding gradient explosion.

**Comment by danpovey** [comment] 2015-09-14 22:39
Another note: it's possible that Pegah's change
-chunk_width=20
-chunk_left_context=20
+chunk_width=10
+chunk_left_context=10
does not correspond to what she ran, and we might have to change it back.
this relates to the durations of the chunks of data that we train on.
Dan

**Comment by naxingyu** [comment] 2015-09-15 10:23
I have a hkust and a swbd setup running, both using Pegah's ami setup.
In the hkust setup, iteration 0 works fine, but the network explodes on 
iteration 1. Training log shows objf jumps from -4.34102 to -6108.87.
The swbd setup seems to be running ok.
Now I start tuning on these two setups.
Any suggestion?

**Comment by vijayaditya** [comment] 2015-09-15 14:09
Hi Xingyu this happens when there is a gradient explosion in one of the intermediate steps.
Could you check what is the clipping threshold you are using. You could try using a smaller clipping threshold

<code> nnet3-am-info \<model-name\> |grep clipping </code>

**Comment by danpovey** [comment] 2015-09-15 18:37
Also, does the objf get worse within all of the individual jobs
train.1.XX.log, or just one of them?
My instinct is that you could try decreasing the max-change values in the
config and/or the learning rates.  But as Vijay said, the gradient clipping
threshold might make a difference too.
Looking at the nnet3-info output in the progress.XX.log might help show
which parameters are exploding, if any- check the stddevs.
Dan

**Comment by vijayaditya** [comment] 2015-09-15 18:41
@naxingyu one other thing, I just pushed in some changes where the default learning rates in the steps/nnet3/lstm/train.sh have been modified. Ensure that you are using the learning rates in this range.

**Comment by naxingyu** [comment] 2015-09-16 02:52
Thanks Dan and Vijay. I checked the latest commits, recompiled the 
binaries, reduced clipping threshold from 10.0 to 5.0, and ensured the 
learning rates in the modified range.
1. hkust setup still explodes from very beginning. When it explodes, it 
happens on all of the individual jobs. 'clipped-proportion' is above 
0.9, on both cell and recurrent components.
2. swbd setup explodes later, in a similar behavior as hkust setup.
=============
I see Vijay commit the min-deriv-time option when I compose this 
comment. I'll try that ASAP.

**Comment by danpovey** [comment] 2015-09-16 02:54
Try smaller learning-rates and/or smaller max-change.
Dan

**Comment by naxingyu** [comment] 2015-09-16 02:55
OK. What 'max-change'? didn't see an option for that...

**Comment by danpovey** [comment] 2015-09-16 02:55
Can you show us an example log where the objf is very bad?  I want to see
if it starts from the beginning of the job, or in the middle of the job.

**Comment by vijayaditya** [comment] 2015-09-16 02:57
@naxingyu When reducing clipping threshold monitor the clipping-proportion in progress*.log. If this is high the objective function usually does not improve. 

you can add this in steps/nnet3/lstm.sh using options
ng_per_element_scale_options=
ng_affine_options=

**Comment by danpovey** [comment] 2015-09-16 02:58
Regarding 'max-change', it may not be in the script, but the
NaturalGradientAffineComponent supports the 'max-change-per-sample' option
whose default value is 0.075 (would be in the line 'component
name=xxx...'), and the NaturalGradientPerElementScaleComponent supports the
'max-change-per-minibatch' option whose default value is 0.5.

Dan

**Comment by naxingyu** [comment] 2015-09-16 03:01
Both. I show you when it happens in the first 10 minibatches.
=====================
```
# Running on g19
# Started at Wed Sep 16 10:16:21 CST 2015
# nnet3-train --print-interval=10 --update-per-minibatch=true 
"nnet3-am-copy --raw=true --learning-rate=0.000596534446947406 
exp/nnet3/lstm_ld5/1.mdl -|" "ark:nnet3-copy-egs --left-context=40 
--right-context=7 ark:exp/nnet3/lstm_ld5/egs/egs.3.ark ark:- | 
nnet3-shuffle-egs --buffer-size=5000 --srand=1 ark:- ark:-| 
nnet3-merge-egs --minibatch-size=100 --measure-output-frames=false ark:- 
ark:- |" exp/nnet3/lstm_ld5/2.1.raw
nnet3-train --print-interval=10 --update-per-minibatch=true 
'nnet3-am-copy --raw=true --learning-rate=0.000596534446947406 
exp/nnet3/lstm_ld5/1.mdl -|' 'ark:nnet3-copy-egs --left-context=40 
--right-context=7 ark:exp/nnet3/lstm_ld5/egs/egs.3.ark ark:- | 
nnet3-shuffle-egs --buffer-size=5000 --srand=1 ark:- ark:-| 
nnet3-merge-egs --minibatch-size=100 --measure-output-frames=false ark:- 
ark:- |' exp/nnet3/lstm_ld5/2.1.raw
LOG (nnet3-train:IsComputeExclusive():cu-device.cc:246) CUDA setup 
operating under Compute Exclusive Mode.
LOG (nnet3-train:FinalizeActiveGpu():cu-device.cc:213) The active GPU is 
[0]: Tesla K20m    free:4705M, used:94M, total:4799M, 
free/total:0.980312 version 3.5
nnet3-am-copy --raw=true --learning-rate=0.000596534446947406 
exp/nnet3/lstm_ld5/1.mdl -
LOG (nnet3-am-copy:main():nnet3-am-copy.cc:96) Copied neural net from 
exp/nnet3/lstm_ld5/1.mdl to raw format as -
nnet3-shuffle-egs --buffer-size=5000 --srand=1 ark:- ark:-
nnet3-copy-egs --left-context=40 --right-context=7 
ark:exp/nnet3/lstm_ld5/egs/egs.3.ark ark:-
nnet3-merge-egs --minibatch-size=100 --measure-output-frames=false ark:- 
ark:-
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.366088, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.79104 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.279167
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.525689, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.41438 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.353512
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.549739, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.84376 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.271185
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.529195, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.7881 exceeds --max-change-per-minibatch=0.5 for this minibatch, 
for Lstm1_w_oc, scaling by factor 0.279627
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.545474, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.82206 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.274415
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.497255, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.92931 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.25916
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.499546, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.36253 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.366964
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.525674, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.80693 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.276712
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.528004, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.40109 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.356866
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) 
Limiting step size using scaling factor 0.504728, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 2.65101 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.188608
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 0-9 is -41.225 over 
19451 frames.
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter 
change 1.06435 exceeds --max-change-per-minibatch=0.5 for this 
minibatch, for Lstm1_w_oc, scaling by factor 0.469769
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 10-19 is -49.1079 over 
19514 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 20-29 is -53.304 over 
19421 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 30-39 is -46.8068 over 
19406 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 40-49 is -35.0044 over 
19538 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 50-59 is -32.7891 over 
19423 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 60-69 is -42.1689 over 
19457 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 70-79 is -34.7181 over 
19393 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 80-89 is -37.7776 over 
19413 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 90-99 is -44.3953 over 
19418 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 100-109 is -40.2744 over 
19495 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 110-119 is -31.8361 over 
19481 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 120-129 is -35.3526 over 
19385 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 130-139 is -36.5132 over 
19468 frames.
LOG (nnet3-copy-egs:main():nnet3-copy-egs.cc:339) Read 20029 
neural-network training examples, wrote 20029
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 140-149 is -33.5093 over 
19444 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 150-159 is -30.1704 over 
19348 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 160-169 is -29.4314 over 
19450 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 170-179 is -25.2375 over 
19356 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 180-189 is -34.1938 over 
19466 frames.
LOG (nnet3-shuffle-egs:main():nnet3-shuffle-egs.cc:103) Shuffled order 
of 20112 neural-network training examples using a buffer (partial 
randomization)
LOG (nnet3-merge-egs:main():nnet3-merge-egs.cc:121) Merged 20029 egs to 201.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average 
objective function for 'output' for minibatches 190-199 is -30.8311 over 
19354 frames.
LOG (nnet3-train:PrintTotalStats():nnet-training.cc:129) Overall average 
objective function for 'output' is -37.2068 over 389248 frames.
LOG (nnet3-train:PrintProfile():cu-device.cc:415) -----
[cudevice profile]
CopyRows    1.52818s
MulColsVec    1.58382s
CuMatrix::SetZero    1.64581s
AddDiagMatMat    2.01596s
AddVec    2.12538s
CopyFromVec<float>    2.17151s
CuVectorBase::ApplyFloor    2.25274s
Set    2.77716s
CuVector::SetZero    3.61297s
MulElements    3.72628s
AddMatVec    3.76281s
AddMat    4.11245s
CuVector::Resize    4.63484s
CuMatrixBase::CopyFromMat(from other CuMatrixBase)    9.23624s
AddMatMat    27.4815s
Total GPU time:    82.4288s (may involve some double-counting)
-----
LOG (nnet3-train:PrintMemoryUsage():cu-allocator.cc:126) Memory usage: 
789164880 bytes currently allocated (max: 807610216); 16182772 currently 
in use by user (max: 538426172); 978/538361 calls to Malloc* resulted in 
CUDA calls.
LOG (nnet3-train:PrintMemoryUsage():cu-allocator.cc:133) Time taken in 
cudaMallocPitch=0.210049, in cudaMalloc=0.0545287, in 
cudaFree=0.00750351, in this->MallocPitch()=1.14464
LOG (nnet3-train:PrintMemoryUsage():cu-device.cc:388) Memory used 
(according to the device): 891871232 bytes.
LOG (nnet3-train:main():nnet3-train.cc:86) Wrote model to 
exp/nnet3/lstm_ld5/2.1.raw
# Accounting: time=103 threads=1
# Finished at Wed Sep 16 10:18:04 CST 2015 with status 0
```

**Comment by naxingyu** [comment] 2015-09-16 03:02
Both. I show you when it happens in the first 10 minibatches.
=====================
```
# Running on g19
# Started at Wed Sep 16 10:16:21 CST 2015
# nnet3-train --print-interval=10 --update-per-minibatch=true "nnet3-am-copy --raw=true --learning-rate=0.000596534446947406 exp/nnet3/lstm_ld5/1.mdl -|" "ark:nnet3-copy-egs --left-context=40 --right-context=7 ark:exp/nnet3/lstm_ld5/egs/egs.3.ark ark:- | nnet3-shuffle-egs --buffer-size=5000 --srand=1 ark:- ark:-| nnet3-merge-egs --minibatch-size=100 --measure-output-frames=false ark:- ark:- |" exp/nnet3/lstm_ld5/2.1.raw 
nnet3-train --print-interval=10 --update-per-minibatch=true 'nnet3-am-copy --raw=true --learning-rate=0.000596534446947406 exp/nnet3/lstm_ld5/1.mdl -|' 'ark:nnet3-copy-egs --left-context=40 --right-context=7 ark:exp/nnet3/lstm_ld5/egs/egs.3.ark ark:- | nnet3-shuffle-egs --buffer-size=5000 --srand=1 ark:- ark:-| nnet3-merge-egs --minibatch-size=100 --measure-output-frames=false ark:- ark:- |' exp/nnet3/lstm_ld5/2.1.raw 
LOG (nnet3-train:IsComputeExclusive():cu-device.cc:246) CUDA setup operating under Compute Exclusive Mode.
LOG (nnet3-train:FinalizeActiveGpu():cu-device.cc:213) The active GPU is [0]: Tesla K20m	free:4705M, used:94M, total:4799M, free/total:0.980312 version 3.5
nnet3-am-copy --raw=true --learning-rate=0.000596534446947406 exp/nnet3/lstm_ld5/1.mdl - 
LOG (nnet3-am-copy:main():nnet3-am-copy.cc:96) Copied neural net from exp/nnet3/lstm_ld5/1.mdl to raw format as -
nnet3-shuffle-egs --buffer-size=5000 --srand=1 ark:- ark:- 
nnet3-copy-egs --left-context=40 --right-context=7 ark:exp/nnet3/lstm_ld5/egs/egs.3.ark ark:- 
nnet3-merge-egs --minibatch-size=100 --measure-output-frames=false ark:- ark:- 
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.366088, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.79104 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.279167
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.525689, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.41438 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.353512
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.549739, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.84376 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.271185
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.529195, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.7881 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.279627
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.545474, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.82206 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.274415
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.497255, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.92931 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.25916
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.499546, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.36253 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.366964
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.525674, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.80693 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.276712
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.528004, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.40109 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.356866
LOG (nnet3-train:GetScalingFactor():nnet-simple-component.cc:1253) Limiting step size using scaling factor 0.504728, for component Lstm1_W_o-xr
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 2.65101 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.188608
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 0-9 is -41.225 over 19451 frames.
WARNING (nnet3-train:Update():nnet-simple-component.cc:1923) Parameter change 1.06435 exceeds --max-change-per-minibatch=0.5 for this minibatch, for Lstm1_w_oc, scaling by factor 0.469769
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 10-19 is -49.1079 over 19514 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 20-29 is -53.304 over 19421 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 30-39 is -46.8068 over 19406 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 40-49 is -35.0044 over 19538 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 50-59 is -32.7891 over 19423 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 60-69 is -42.1689 over 19457 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 70-79 is -34.7181 over 19393 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 80-89 is -37.7776 over 19413 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 90-99 is -44.3953 over 19418 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 100-109 is -40.2744 over 19495 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 110-119 is -31.8361 over 19481 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 120-129 is -35.3526 over 19385 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 130-139 is -36.5132 over 19468 frames.
LOG (nnet3-copy-egs:main():nnet3-copy-egs.cc:339) Read 20029 neural-network training examples, wrote 20029
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 140-149 is -33.5093 over 19444 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 150-159 is -30.1704 over 19348 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 160-169 is -29.4314 over 19450 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 170-179 is -25.2375 over 19356 frames.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 180-189 is -34.1938 over 19466 frames.
LOG (nnet3-shuffle-egs:main():nnet3-shuffle-egs.cc:103) Shuffled order of 20112 neural-network training examples using a buffer (partial randomization)
LOG (nnet3-merge-egs:main():nnet3-merge-egs.cc:121) Merged 20029 egs to 201.
LOG (nnet3-train:PrintStatsForThisPhase():nnet-training.cc:121) Average objective function for 'output' for minibatches 190-199 is -30.8311 over 19354 frames.
LOG (nnet3-train:PrintTotalStats():nnet-training.cc:129) Overall average objective function for 'output' is -37.2068 over 389248 frames.
LOG (nnet3-train:PrintProfile():cu-device.cc:415) -----
[cudevice profile]
CopyRows	1.52818s
MulColsVec	1.58382s
CuMatrix::SetZero	1.64581s
AddDiagMatMat	2.01596s
AddVec	2.12538s
CopyFromVec<float>	2.17151s
CuVectorBase::ApplyFloor	2.25274s
Set	2.77716s
CuVector::SetZero	3.61297s
MulElements	3.72628s
AddMatVec	3.76281s
AddMat	4.11245s
CuVector::Resize	4.63484s
CuMatrixBase::CopyFromMat(from other CuMatrixBase)	9.23624s
AddMatMat	27.4815s
Total GPU time:	82.4288s (may involve some double-counting)
-----
LOG (nnet3-train:PrintMemoryUsage():cu-allocator.cc:126) Memory usage: 789164880 bytes currently allocated (max: 807610216); 16182772 currently in use by user (max: 538426172); 978/538361 calls to Malloc* resulted in CUDA calls.
LOG (nnet3-train:PrintMemoryUsage():cu-allocator.cc:133) Time taken in cudaMallocPitch=0.210049, in cudaMalloc=0.0545287, in cudaFree=0.00750351, in this->MallocPitch()=1.14464
LOG (nnet3-train:PrintMemoryUsage():cu-device.cc:388) Memory used (according to the device): 891871232 bytes.
LOG (nnet3-train:main():nnet3-train.cc:86) Wrote model to exp/nnet3/lstm_ld5/2.1.raw
# Accounting: time=103 threads=1
# Finished at Wed Sep 16 10:18:04 CST 2015 with status 0
```

**Comment by danpovey** [comment] 2015-09-16 03:04
OK, but there are two possibilities here. It could have diverged already
within the first few minibatches, or it could have been that the model was
already bad.  What does the compute_prob_train.1.log look like, i.e. what
is the probability there?

Dan

**Comment by vijayaditya** [comment] 2015-09-16 03:04
@naxingyu  
Could you submit a pull request for your hkust and swbd recipes. 
You could update the pull request as you progress and it would easier for everyone to keep track of your local setup.


BTW in your current setup the problem is due to <code> --left-context=40 </code>. This was due to a bug in make_configs.py introduced in a commit from Pegah. I have removed it in the latest commit.

**Comment by naxingyu** [comment] 2015-09-16 10:37
compute_prob_train.1.log looks like this:
Overall log-likelihood for 'output' is -43.8004 per frame, over 4000 frames.
Already bad... And progress.1.log looks like this:
component name=Lstm1_c type=ClipGradientComponent, dim=1024, 
norm-based-clipping=true, clipping-threshold=5, clipped-proportion=0.924855
component name=Lstm1_r type=ClipGradientComponent, dim=256, 
norm-based-clipping=true, clipping-threshold=5, clipped-proportion=0.742215
======================
OK I checked train.0.1.log and train.0.2.log, job1 exploded and job2 ran 
fine. So issue is that 0.1.mdl is already bad before averaging.
I have checked in Vijay's latest commit and will update tomorrow.

**Comment by danpovey** [comment] 2015-09-16 19:47
I followed up with this text by email but it didn't show up here- very strange.  I'll bring it up with GitHub support staff.



"OK, there must be a script bug then.  Because the way the script is supposed to work, on iteration zero (and any iteration when you just added a new layer), it should take the job with the best likelihood.  Obviously it is not doing that. Perhaps it is not able to parse the liklelihood from the script because it produces output different from nnet2.  @vpeddinti, please look at this urgently!"

**Comment by vijayaditya** [comment] 2015-09-16 20:01
I verified that the script is selecting the model, but in @naxingyu 's case all the models would have diverged. This is very probable as he was using <code> --left-context 40 </code> without <code> optimization.min-deriv-time </code>. This essentially means that the model was getting updated with a gradient which has been back-propagated 50-60 time steps (depending on the frames_per_eg). Hence this gradient would have a high probability of explosion/vanishing. 

In the updated recipe <code> optimization.min-deriv-time </code> is used to restrict back-prop to 20 time steps. So he might not see any of these problems. Further the left-context is also reduced to 20 (it was previously taken as 40 due to a bug).

**Comment by danpovey** [comment] 2015-09-16 22:46
Vijay:
@naxingyu said in this thread, "OK I checked train.0.1.log and
train.0.2.log, job1 exploded and job2 ran fine. So issue is that 0.1.mdl is
already bad before averaging.".
But in this case it should have chosen the model from train.0.2.log.
@vpeddinti: I notice that the script contains a reference to num_jobs_nnet,
which seems to be an undefined variable.
Dan

**Comment by naxingyu** [comment] 2015-09-17 02:18
Thanks. Now I use Vijay's updated scripts with reduced lrates (0.0002 
and 0.00002). Options are "--optimization.min-deriv-time=0" and 
"--left-context=20 --right-context=7".
iter0 and iter1 works fine, with prob_train of -3.98025 and -3.45653. 
The network explodes at iter2, but only on job train.2.1.
After that, 3.1.raw is copied into 3.mdl (as shown in select.2.log), 
which is not right.
I tested the selecting perl command and found that it was looking for 
"log-prob-per-frame=(\S+)" expression which is not a 
"to-be-parsed-by-a-script" variable in nnet3 (was in nnet2). So the 
script always select the first net regardless of "log-prob-per-frame".

**Comment by danpovey** [comment] 2015-09-17 02:21
If you can fix the script yourself, please do via a pull request.

Dan

**Comment by danpovey** [comment] 2015-09-17 02:25
BTW, to keep you abreast of the latest developments.

 - Vijay has been experimenting with a version of the code supporting
momentum, in a pull request that I created.  So far it doesn't seem to help
our standard setup, but when I increase the learning rate a lot it does
seem to prevent instability (but in those situations the likelihood still
degrades, just not nearly as badly).
 - Right now I'm increasingly convinced that the problem is that the
parameters are getting too large and the sigmoids are getting
oversaturated.  My proposed  solution is to decrease the parameters
slightly (e.g. by a factor of 0.95) on each iteration-- at least, in early
epochs.  An option could be added to nnet3-copy or nnet3-am-copy to scale
the parameters using ScaleNnet().  I know this  a bit odd, but it can be
viewed as almost equivalent to applying l2 regularization.  Do you have
time to try this?  I'm convinced it will help us get to a better place in
parameter space.

Dan

**Comment by naxingyu** [comment] 2015-09-17 02:31
OK. My plan is to fix this selecting issue first, then tune 'max-change' 
options as you suggested.
After that, try the scaling/l2-regularizing stuff.

Best,
Xingyu

**Comment by danpovey** [comment] 2015-09-17 02:34
Thanks!
Actually I think Vijay was spending some time tuning the max-change, but
I'm not aware that he saw any improvement.  In any case, he can let us know
what the issue was.  So it might be better if you just go straight to the
scaling thing.
If you make the pull request in
https://github.com/kaldi-asr/kaldi/pull/143
which makes momentum=0.9 the default, I'm fairly confident that you will
not get the catastrophic divergence that you are seeing.
Dan

**Comment by danpovey** [comment] 2015-09-17 02:40
... I mean, if you make that pull request your starting point.

**Comment by danpovey** [comment] 2015-09-17 02:50
I just merged that pull request (but made 0.0 the default for momentum).
Likely if you add --momentum 0.8 to the command line it will stabilize the
update without affecting convergence.
Dan

**Comment by naxingyu** [comment] 2015-09-17 02:51
Got it! Thanks.

**Comment by vijayaditya** [comment] 2015-09-17 03:27
Was offline for few hours, back to implementing the nnet-am-copy with scaling. 
Using lower max-change options didn't affect a great change (objf of -3.56 vs -3.54).

**Closed** 2015-11-19 22:39 UTC
