### ISSUE TITLE
How to transcribe numbers as digits in stead of words?

### ISSUE THREAD

**Issue by kkoenen** [kaldi-asr/kaldi#1836] opened 2017-08-22 10:06 UTC
I use Kaldi-asr with the custom Dutch language models. It works fine, but I need numbers transcribed as digits (153.425) in stead of words (hundredfiftythreethousand...).

What is the best way to do that?

**Comment by jtrmal** [comment] 2017-08-22 14:55
probably you will have to write your own code to postprocess the text
correctly.
y.

**Comment by kkoenen** [comment] 2017-08-26 14:40
That I don't believe. Furthermore; it's undoable. You tell me what the code should be to 'translate' any number between 0 and let's say 1.000.000 from text to digits.. There must be an easier way.

**Comment by jtrmal** [comment] 2017-08-26 15:25
It's even more difficult than you can imagine if it should be done in a way that would be general enough. Text "one thousand and twenty three" can mean different numbers. When you ask about an easier way, you probably mean easier for you. And I'm not aware of anything. I;m closing this, as it's really not a problem of kaldi and not a bug. I suggest you ask on the kaldi-help mailing list, hopefully someone will be able to help you more.

**Closed by jtrmal** 2017-08-26 15:25 UTC
