### ISSUE TITLE
Build error: undefined reference to `FLAGS_fst_field_separator[abi:cxx11]'

### ISSUE THREAD

**Issue by Wolfgange3311999** [kaldi-asr/kaldi#938] opened 2016-08-02 05:10 UTC
I ran `check_dependencies.sh` (nothing missing), ran make `tools/` successfully, configured with `./configure --openblas-root=../tools/OpenBLAS/install` after successfully compiling OpenBLAS, as suggested by configure since the package isn't available for my system, and then I ran `make` in `src/`. Even after cleaning with `make clean` I run into the following error:
```build
/tmp/cc1VscBX.o: In function `void fst::ReadFstKaldi<fst::ArcTpl<fst::TropicalWeightTpl<float> > >(std::istream&, bool, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::TropicalWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > >*)':
/home/matthew/Documents/GitHub/kaldi/src/bin/../fstext/kaldi-fst-io-inl.h:107: undefined reference to `FLAGS_fst_field_separator[abi:cxx11]'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'align-equal-compiled' failed
```

Note that I am running Solus which is a more obscure Linux distro written mostly from scratch meaning it is does not have roots in anything more common like Debian. Any help would be greatly appreciated. Let me know if this is better suited for the mailing list.

**Comment by jtrmal** [comment] 2016-08-02 05:27
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

If you get linker errors about undefined references to symbols that involve
types in the std::__cxx11 namespace or the tag [abi:cxx11] then it probably
indicates that you are trying to link together object files that were
compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This
commonly happens when linking to a third-party library that was compiled
with an older version of GCC. If the third-party library cannot be rebuilt
with the new ABI then you will need to recompile your code with the old ABI.

So I guess you should check flags of openfst vs kaldi to see if there is
something that could cause "_GLIBCXX_USE_CXX11_ABI" to be defined (or
perhaps the variable itself being defined)


y.

**Comment by danpovey** [comment] 2016-08-02 05:42
Is it possible that OpenFst was installed as some kind of system package?
If so, it could cause version mismatches, and anyway would likely cause
crashes later on.  You might have to remove that package for things to work
right.
Dan

**Comment by Wolfgange3311999** [comment] 2016-08-03 04:57
@danpovey No, OpenFst isn't installed nor available for my system beyond compiling it myself. Only yesterday I compiled OpenFst 1.4.1 and installed with `sudo make install`. I made sure the generated Makefile had `C++0x` as a `CXXFLAG`.

@jtrmal Well, I compiled OpenFst recently with the same compiler I'm using now which is `5.3.0`. Could there be another library that would relate to `FLAGS_fst_field_separator`?

**Comment by danpovey** [comment] 2016-08-03 05:28
Does kaldi.mk have the flag

-std=c++0x

in CXXFLAGS?

The configure should add this if it detects that you have installed OpenFst
1.4.1 in tools/.

However, if you have manually installed OpenFst1.4.1 at the system level,
and there is a different version in tools/, obviously it could cause a
mismatch.

**Comment by danpovey** [comment] 2016-08-03 05:32
Closing this issue as the problem is that you have installed OpenFst in system space which is conflicting with Kaldi.

**Comment by danpovey** [comment] 2016-08-03 06:07
BTW, I just modified the extras/check_dependencies.sh script to check more robustly whether OpenFst has been installed in system space.

**Closed** 2016-08-21 20:49 UTC
